### ISSUE TITLE
ibm_db brakes docker build pipeline 

### ISSUE THREAD

**Issue by csantanapr** [ibm-functions/runtime-python#65]
The python library `ibm_db` is having problems installing due to the download of the driver

Errors in travis
```
Downloading https://files.pythonhosted.org/packages/3f/61/389c6decacfed61c2724005b8c2be61f2c699f731b53af13517e5a0e6e98/ibm_db-2.0.9.tar.gz (782kB)
    Complete output from command python setup.py egg_info:
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4rqrzt32/ibm-db/setup.py", line 164, in <module>
        file_stream = BytesIO(request.urlopen(url).read())
      File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by csantanapr** [comment]
Issue already opened against ibm_db package here https://github.com/ibmdb/python-ibmdb/issues/350

**Comment by SabaKauser** [comment]
Hello Carlos,
I have written to the maintainer.

**Comment by csantanapr** [comment]
This is fixed now
